### ISSUE TITLE
What are you up to right now?

### ISSUE THREAD

**Issue by claudiordgz** [joelhooks/ama#1]
Besides this AMA of course... like personal & work projects

**Comment by joelhooks** [comment]
For the most part I spend my days working on egghead.io. Programming/tinkering with the site (Ruby on Rails) and content. I don't produce a lot of content, but I facilitate most of the content with a lot of help from @johnlindquist. 

https://instructor.egghead.io 

I also recently moved my partner, our 4 kids, 2 dogs, and 3 cats from Ft Worth Texas to Vancouver Washington (outside of Portland) 😳

**Comment by claudiordgz** [comment]
I hate the segregation I see in Atlanta, specially for my kid's development, me and my partner already decided on leaving. Having said that...why did you leave Texas?

**Comment by joelhooks** [comment]
I lived there for 36 years, and love the Pacific Northwest. It's where I was born (Spokane), and as a family we love outdoor adventure activities. Texas didn't have them!

Also, Texas summers are brutal hot and humid! This is a nice change :>

**Comment by claudiordgz** [comment]
Btw I don't know anything about Portland, I have read only good things... with this exception http://www.shouldimovetoportland.com/

**Comment by joelhooks** [comment]
I think that was made by somebody in Portland to send more people to Seattle ;P
