### ISSUE TITLE
What is the most wanted feature your content creators want?

### ISSUE THREAD

**Issue by claudiordgz** [joelhooks/ama#2]

**Comment by joelhooks** [comment]
It is probably better statistics. I don't provide very good ones at the moment.

We have a huge initiative in the works to implement some recommendations given to use by @nickdpi following a research engagement. The idea is to build out a world class instructor portal and to really cater to them and make creating lessons for egghead as easy and rewarding as possible.

We want to be a boutique publishing house that pampers content creators and makes the whole thing painless. Most of the big name publishers have "lost the plot" in that regard.
