### ISSUE TITLE
Classic question? 

### ISSUE THREAD

**Issue by dsylvesteriii** [joelhooks/ama#3]
angular 2 or react? And why?

**Comment by joelhooks** [comment]
I use React on egghead with [react-rails](https://github.com/reactjs/react-rails). It is "fully baked" - which is nice. The `react-rails` gem allows us to drop in ES6 React components very easily.

At the end of the day this is a question for your team that is hard to answer. In my view the most important thing at the moment is that you build applications in a component-centric style, use a Redux-style architecture (ngrx/store, ng-redux, redux, etc) and follow that pattern as it is very nice.

TypeScript is wonderful, but React for the most part is "just JavaScript" which I think is nice as well.

I'd be happy using either in the right situation! Both are solid well crafted tools backed by strong companies and wicked smart teams.

**Comment by jonbcampos** [comment]
I'm going to have to check out that gem. RoR is always just a fun language to use
